### ISSUE TITLE
Balance Medical wake up to number of players on

### ISSUE THREAD

**Issue by hehe3301** [AdamWaldie/A3-CAVASTASI#12]
**What, in your opinion, is currently wrong with the balance?**
When playing alone one lucky shot by the AI can waste large amounts of time when by yourself.

**Describe the solution you'd like**
Could the wake up chance scale to the number of players or medics? more medics less auto wake up chance?

**Describe alternatives you've considered**
Hard to play in small groups, hard to get larger groups without being on

**Comment by AdamWaldie** [comment]
Ill look into this. But as it stands, we have a really high auto-wakeup chance of 60-70% every cycle.

**Comment by AdamWaldie** [comment]
Not possible to change setting mid mission.
